# Generated by Django 3.2.3 on 2021-06-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artista', models.TextField(max_length=50, verbose_name='Nombre')),
                ('pais_artista', models.TextField(max_length=50, verbose_name='Pais')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Historia')),
                ('foto', models.ImageField(upload_to='proyects', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.TextField(max_length=20, verbose_name='Nombre y Apellido')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('mensaje', models.TextField(max_length=300, verbose_name='Mensaje')),
                ('imagen', models.ImageField(upload_to='proyects', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30, verbose_name='Nombre')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
    ]
