# Generated by Django 3.2.3 on 2021-06-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Historia'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre_artista',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='pais_artista',
            field=models.CharField(max_length=50, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre_contacto',
            field=models.CharField(max_length=20, verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
