# Generated by Django 3.2.3 on 2021-06-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210605_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Historia'),
        ),
    ]
