# Generated by Django 3.2.3 on 2021-06-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210605_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
